LondonDataServices.IDecide.Core.Tests.Unit/LondonDataServices.IDecide.Core.Tests.Unit.csproj
LondonDataServices.IDecide.Core/Brokers/Securities/ISecurityAuditBroker.cs
LondonDataServices.IDecide.Core/Brokers/Securities/SecurityAuditBroker.cs
LondonDataServices.IDecide.Core/LondonDataServices.IDecide.Core.csproj
LondonDataServices.IDecide.Manage.Server.Tests.Acceptance/LondonDataServices.IDecide.Manage.Server.Tests.Acceptance.Tests.Acceptance.csproj
LondonDataServices.IDecide.Manage.Server.Tests.Integration/LondonDataServices.IDecide.Manage.Server.Tests.Integration.csproj
LondonDataServices.IDecide.Manage.Server.Tests.Unit/LondonDataServices.IDecide.Manage.Server.Tests.Unit.csproj
LondonDataServices.IDecide.Manage.Server/LondonDataServices.IDecide.Manage.Server.csproj
LondonDataServices.IDecide.Portal.Server.Tests.Unit/LondonDataServices.IDecide.Portal.Server.Tests.Unit.csproj
LondonDataServices.IDecide.Portal.Server/LondonDataServices.IDecide.Portal.Server.csproj
LondonDataServices.IDecide.Portal.Tests.Acceptance/LondonDataServices.IDecide.Portal.Tests.Acceptance.csproj
LondonDataServices.IDecide.Portal.Tests.Integration/LondonDataServices.IDecide.Portal.Tests.Integration.csproj

BROKERS: Security Audit Broker

---

LondonDataServices.IDecide.Manage.Client/src/components/layouts/loginUnauth.tsx
LondonDataServices.IDecide.Portal.Client/src/components/confirmCode/confirmCode.tsx
LondonDataServices.IDecide.Portal.Client/src/components/confirmation/confirmation.tsx
LondonDataServices.IDecide.Portal.Client/src/components/home/home.tsx
LondonDataServices.IDecide.Portal.Client/src/components/layouts/header.tsx
LondonDataServices.IDecide.Portal.Client/src/components/leftProgress/leftProgress.tsx
LondonDataServices.IDecide.Portal.Client/src/components/optInOptOut/optInOptOut.tsx
LondonDataServices.IDecide.Portal.Client/src/components/positiveConfirmation/positiveConfirmation.tsx
LondonDataServices.IDecide.Portal.Client/src/components/root.tsx
LondonDataServices.IDecide.Portal.Client/src/components/searchByDetails/searchByDetails.tsx
LondonDataServices.IDecide.Portal.Client/src/styles/components.scss
LondonDataServices.IDecide.Portal.Client/src/styles/responsive.scss

CODE RUB: Responsiveness

---

LondonDataServices.IDecide.Core/Brokers/Storages/Sql/StorageBroker.Decision.Configurations.cs
LondonDataServices.IDecide.Core/Migrations/20250813142558_AddInitialMigration.Designer.cs
LondonDataServices.IDecide.Core/Migrations/20250813142558_AddInitialMigration.cs
LondonDataServices.IDecide.Core/Migrations/StorageBrokerModelSnapshot.cs
LondonDataServices.IDecide.Core/Models/Foundations/Decisions/Decision.cs

Closes [AB#23884](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/23884)

DATA: Decision

---

LondonDataServices.IDecide.Core/Brokers/Storages/Sql/StorageBroker.Consumer.Configurations.cs
LondonDataServices.IDecide.Core/Brokers/Storages/Sql/StorageBroker.cs
LondonDataServices.IDecide.Core/Migrations/20250819132850_AddInitialMigration.Designer.cs
LondonDataServices.IDecide.Core/Migrations/20250819132850_AddInitialMigration.cs
LondonDataServices.IDecide.Core/Migrations/StorageBrokerModelSnapshot.cs
LondonDataServices.IDecide.Core/Models/Foundations/Consumers/Consumer.cs

Closes [AB#24000](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/24000)

DATA: Consumer

---

LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/Decisions/DecisionServiceTests.cs
LondonDataServices.IDecide.Core/Brokers/Storages/Sql/StorageBroker.ConsumerStatus.Configurations.cs
LondonDataServices.IDecide.Core/Brokers/Storages/Sql/StorageBroker.cs
LondonDataServices.IDecide.Core/Migrations/20250820094222_ConsumerStatus.Designer.cs
LondonDataServices.IDecide.Core/Migrations/20250820094222_ConsumerStatus.cs
LondonDataServices.IDecide.Core/Models/Foundations/Consumers/ConsumerStatus.cs
LondonDataServices.IDecide.Core/Models/Foundations/Decisions/Decision.cs

Closes [AB#23993](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/23993)

DATA: ConsumerStatus

---

LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/ConsumerStatuses/ConsumerStatusServiceTests.Modify.Exceptions.cs
LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/ConsumerStatuses/ConsumerStatusServiceTests.Modify.Logic.cs
LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/ConsumerStatuses/ConsumerStatusServiceTests.Modify.Validations.cs
LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/ConsumerStatuses/ConsumerStatusServiceTests.cs
LondonDataServices.IDecide.Core/Models/Foundations/ConsumerStatuses/Exceptions/ConsumerStatusDependencyValidationException.cs
LondonDataServices.IDecide.Core/Models/Foundations/ConsumerStatuses/Exceptions/ConsumerStatusServiceException.cs
LondonDataServices.IDecide.Core/Models/Foundations/ConsumerStatuses/Exceptions/LockedConsumerStatusException.cs
LondonDataServices.IDecide.Core/Models/Foundations/ConsumerStatuses/Exceptions/NotFoundConsumerStatusException.cs
LondonDataServices.IDecide.Core/Services/Foundations/ConsumerStatuses/ConsumerStatusService.Exceptions.cs
LondonDataServices.IDecide.Core/Services/Foundations/ConsumerStatuses/ConsumerStatusService.Validations.cs
LondonDataServices.IDecide.Core/Services/Foundations/ConsumerStatuses/ConsumerStatusService.cs
LondonDataServices.IDecide.Core/Services/Foundations/ConsumerStatuses/IConsumerStatusService.cs

Closes [AB#23996](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/23996)

FOUNDATIONS: Modify ConsumerStatus

---

LondonDataServices.IDecide.Core.Tests.Unit/Services/Orchestrations/Patients/PatientOrchestrationServiceTests.CheckIfIsAuthenticatedUserWithRequiredRole.Logic.cs
LondonDataServices.IDecide.Core.Tests.Unit/Services/Orchestrations/Patients/PatientOrchestrationServiceTests.GenerateNewPatientWithCodeAsync.Logic.cs
LondonDataServices.IDecide.Core.Tests.Unit/Services/Orchestrations/Patients/PatientOrchestrationServiceTests.RecordPatientInformation.Exceptions.cs
LondonDataServices.IDecide.Core.Tests.Unit/Services/Orchestrations/Patients/PatientOrchestrationServiceTests.RecordPatientInformation.Logic.cs
LondonDataServices.IDecide.Core.Tests.Unit/Services/Orchestrations/Patients/PatientOrchestrationServiceTests.RecordPatientInformation.Validations.cs
LondonDataServices.IDecide.Core.Tests.Unit/Services/Orchestrations/Patients/PatientOrchestrationServiceTests.UpdatePatientWithNewCode.Logic.cs
LondonDataServices.IDecide.Core/Brokers/Securities/ISecurityBroker.cs
LondonDataServices.IDecide.Core/Brokers/Securities/SecurityBroker.cs
LondonDataServices.IDecide.Core/Services/Orchestrations/Patients/IPatientOrchestrationService.cs
LondonDataServices.IDecide.Core/Services/Orchestrations/Patients/PatientOrchestrationService.Validations.cs
LondonDataServices.IDecide.Core/Services/Orchestrations/Patients/PatientOrchestrationService.cs

CLOSES [AB#24356](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/24356)

BROKERS: Security Update Captcha Validation

---

LondonDataServices.IDecide.Manage.Server.Tests.Unit/Controllers/PatientDecisions/PatientDecisionControllerTests.PostPatientDecision.Exceptions.cs
LondonDataServices.IDecide.Manage.Server.Tests.Unit/Controllers/PatientDecisions/PatientDecisionControllerTests.PostPatientDecision.Logic.cs
LondonDataServices.IDecide.Manage.Server.Tests.Unit/Controllers/PatientDecisions/PatientDecisionControllerTests.PostPatientDecision.Security.cs
LondonDataServices.IDecide.Manage.Server.Tests.Unit/Controllers/PatientDecisions/PatientDecisionControllerTests.cs
LondonDataServices.IDecide.Manage.Server.Tests.Unit/LondonDataServices.IDecide.Manage.Server.Tests.Unit.csproj
LondonDataServices.IDecide.Manage.Server/Controllers/PatientDecisionController.cs

CLOSES [AB#24159](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/24159)

CONTROLLERS: PatientDecision PostPatientDecision Management

---

LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/ConsumerStatuses/ConsumerStatusServiceTests.RetrieveAll.Exceptions.cs
LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/ConsumerStatuses/ConsumerStatusServiceTests.RetrieveAll.Logic.cs
LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/ConsumerStatuses/ConsumerStatusServiceTests.cs
LondonDataServices.IDecide.Core/Services/Foundations/ConsumerStatuses/ConsumerStatusService.Exceptions.cs
LondonDataServices.IDecide.Core/Services/Foundations/ConsumerStatuses/ConsumerStatusService.cs
LondonDataServices.IDecide.Core/Services/Foundations/ConsumerStatuses/IConsumerStatusService.cs

Closes [AB#23997](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/23997)

FOUNDATIONS: RetrieveAll ConsumerStatuses

---

LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/ConsumerStatuses/ConsumerStatusServiceTests.RetrieveById.Exceptions.cs
LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/ConsumerStatuses/ConsumerStatusServiceTests.RetrieveById.Logic.cs
LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/ConsumerStatuses/ConsumerStatusServiceTests.RetrieveById.Validations.cs
LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/Consumers/ConsumerServiceTests.RetrieveById.Logic.cs
LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/Consumers/ConsumerServiceTests.RetrieveById.Validations.cs
LondonDataServices.IDecide.Core/Services/Foundations/ConsumerStatuses/ConsumerStatusService.Validations.cs
LondonDataServices.IDecide.Core/Services/Foundations/ConsumerStatuses/ConsumerStatusService.cs
LondonDataServices.IDecide.Core/Services/Foundations/ConsumerStatuses/IConsumerStatusService.cs

Closes [AB#23998](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/23998)

FOUNDATIONS: ConsumerStatus RetrieveById

---

LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/ConsumerStatuses/ConsumerStatusServiceTests.RemoveById.Exceptions.cs
LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/ConsumerStatuses/ConsumerStatusServiceTests.RemoveById.Logic.cs
LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/ConsumerStatuses/ConsumerStatusServiceTests.RemoveById.Validations.cs
LondonDataServices.IDecide.Core/Services/Foundations/ConsumerStatuses/ConsumerStatusService.cs
LondonDataServices.IDecide.Core/Services/Foundations/ConsumerStatuses/IConsumerStatusService.cs

Closes [AB#23999](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/23999)

FOUNDATIONS: ConsumerStatus RemoveById

---

.github/copilot-instructions.md
LondonDataServices.IDecide.Core.Tests.Unit/Services/Orchestrations/Decisions/DecisionOrchestrationServiceTests.VerifyAndRecordDecision.Logic.cs
LondonDataServices.IDecide.Core/Services/Orchestrations/Decisions/DecisionOrchestrationService.cs

CLOSES [AB#24775](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/24775)

ORCHESTRATIONS: Decision VerifyAndRecordDecision refactor

---

LondonDataServices.IDecide.Core/Brokers/Securities/ISecurityBroker.cs
LondonDataServices.IDecide.Core/Brokers/Securities/SecurityBroker.cs

Closes [AB#24483](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/24483)

BROKERS: Security - GetHeaderAsync

---

LondonDataServices.IDecide.Portal.Client/playwright.config.ts

FIXES [AB#24900](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/24900)

CODE RUB: Fix Playwright

---

LondonDataServices.IDecide.Portal.Client/playwright.config.ts

closes [AB#24897](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/24897)

CODE RUB: Listening to Copilot

---

LondonDataServices.IDecide.Portal.Server/appsettings.ContinuousIntegration.json

FIXES [AB#24900](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/24900)

CODE RUB: Update Connection string name  to match

---

LondonDataServices.IDecide.Portal.Client/playwright.config.ts
LondonDataServices.IDecide.Portal.Server/LondonDataServices.IDecide.Portal.Server.csproj

FIXES [AB#24900](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/24900)

CODE RUB: Another change for playwright

---

LondonDataServices.IDecide.Core.Tests.Unit/Services/Foundations/Pds/PdsServiceTests.cs
LondonDataServices.IDecide.Core/Extensions/Patients/PatientExtension.cs
LondonDataServices.IDecide.Core/LondonDataServices.IDecide.Core.csproj
LondonDataServices.IDecide.Core/Services/Foundations/Pds/PdsService.cs
LondonDataServices.IDecide.Manage.Client/src/components/searchByDetails/searchByDetails.tsx
LondonDataServices.IDecide.Manage.Server.Tests.Acceptance/Apis/PatientSearches/PatientSearchTests.PostPatientSearch.cs
LondonDataServices.IDecide.Manage.Server.Tests.Acceptance/Brokers/TestWebApplicationFactory.cs
LondonDataServices.IDecide.Manage.Server/Program.cs
LondonDataServices.IDecide.Manage.Server/appsettings.json
LondonDataServices.IDecide.Portal.Client/src/components/searchByDetails/searchByDetails.tsx
LondonDataServices.IDecide.Portal.Server.Tests.Acceptance/Apis/PatientCodes/PatientCodeTests.PostPatientGenerationRequest.cs
LondonDataServices.IDecide.Portal.Server.Tests.Acceptance/Apis/PatientSearches/PatientSearchTests.PostPatientSearch.Logic.cs
LondonDataServices.IDecide.Portal.Server.Tests.Acceptance/Apis/PatientSearches/PatientSearchTests.RecordPatientInformation.cs
LondonDataServices.IDecide.Portal.Server.Tests.Acceptance/Brokers/TestWebApplicationFactory.cs
LondonDataServices.IDecide.Portal.Server/LondonDataServices.IDecide.Portal.Server.csproj
LondonDataServices.IDecide.Portal.Server/Program.cs
LondonDataServices.IDecide.Portal.Server/appsettings.json

CLOSES [AB#25287](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/25287)

CODE-RUB: PDS and notifications wire-up

---

LondonDataServices.IDecide.Portal.Client/src/components/confirmation/confirmation.tsx
LondonDataServices.IDecide.Portal.Client/tests/searchbynhsnumber.spec.ts

Fixes [AB#25296](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/25296)

CODE RUB: Update OnError Checks to match

---

LondonDataServices.IDecide.Portal.Client/src/brokers/apiBroker.frontendConfigurationBroker.ts
LondonDataServices.IDecide.Portal.Client/src/components/confirmCode/confirmCode.tsx
LondonDataServices.IDecide.Portal.Client/src/components/positiveConfirmation/positiveConfirmation.tsx
LondonDataServices.IDecide.Portal.Client/src/hooks/useCountdownTimer.tsx
LondonDataServices.IDecide.Portal.Client/src/locales/en/translation.json
LondonDataServices.IDecide.Portal.Client/src/pages/homePage.tsx
LondonDataServices.IDecide.Portal.Server/appsettings.json

FIXES [AB#25416](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/25416)

CODE RUB: Countdown for Resend and style for home page
